### ISSUE TITLE
Alternative module

### ISSUE THREAD

**Issue by gorriecoe** [thewebmen/silverstripe-menustructure#1]
Hi @michelsteege,  I don't know if you would be interested but I have made a similar module.  https://github.com/gorriecoe/silverstripe-menu.  It allows nestable and flat menus.  MenuLinks extends https://github.com/gorriecoe/silverstripe-link to provide plenty of options.

**Comment by michelsteege** [comment]
Hi @gorriecoe It looks like a great module but i created this module for a project where we need full control over the code but maybe for a next project! Thanks for the links 👍

**Comment by gorriecoe** [comment]
All good.  I just saw it come up on my feed and thought I would let you know.
